services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    networks:
      - factory-net
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  nodered:
    image: nodered/node-red:latest
    container_name: factory-gateway
    networks:
      - factory-net
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./nodered-data:/data

  sensor:
    build:
      context: ./sensor
      dockerfile: Dockerfile
    container_name: temp-sensor
    networks:
      - factory-net
    environment:
      - MQTT_BROKER_HOST=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=factory/temperature
      - SENSOR_ID=sensor-1
      - PUBLISH_INTERVAL=1.0

networks:
  factory-net:
    external: true
    name: factory-net
